builds:
  - id: eureka-cli
    dir: ./eureka-cli
    binary: eureka-cli # Optional: rename the output binary
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-s -w"
