# Profile
profile: 
  name: minimal
# Applications
applications:
  name: app-minimal
  version: 1.0.0
  platform: base
  fetch-descriptors: false
# Registry
registry: 
  registry-url: https://folio-registry.dev.folio.org
  sidecar-image: folioci/folio-module-sidecar:1.1.0-SNAPSHOT.90
  folio-install-json-url: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/install.json
  eureka-install-json-url: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/eureka-platform.json
# Environment
environment:
  # General
  ENV: folio
  # PostgeSQL
  DB_HOST: db.eureka
  DB_PORT: 5432
  DB_DATABASE: okapi
  DB_USERNAME: okapi_rw
  DB_PASSWORD: superAdmin
  # Kafka
  KAFKA_HOST: kafka.eureka
  KAFKA_PORT: 9092
  # Elasticsearch
  ELASTICSEARCH_URL: http://host.docker.internal:9200
  # AWS S3/MinIO
  AWS_URL: http://host.docker.internal:9000
  AWS_REGION: us-east-1
  AWS_BUCKET: example-bucket
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  S3_IS_AWS: false
  S3_URL: http://host.docker.internal:9000
  S3_REGION: us-east-1
  S3_ACCESS_KEY_ID: minioadmin
  S3_SECRET_ACCESS_KEY: minioadmin
  S3_BUCKET: example-bucket
  SPLIT_FILES_ENABLED: true
  # Okapi
  OKAPI_URL: http://api-gateway.eureka:8000
  # Consortia
  SYSTEM_USER_PASSWORD: system_user_password
  # Java
  JAVA_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -XX:MaxRAMPercentage=90.0 -Xms256m -Xmx512m"
  # Management
  MOD_AUTHTOKEN_URL: http://mod-authtoken.eureka:8081
  MT_URL: http://mgr-tenants.eureka:8081
  AM_CLIENT_URL: http://mgr-applications.eureka:8081
  KONG_ADMIN_URL: http://api-gateway.eureka:8001
  # Keycloak 
  KC_URL: http://keycloak.eureka:8080
  KC_ADMIN_CLIENT_ID: superAdmin
  KC_ADMIN_USERNAME: admin
  KC_ADMIN_PASSWORD: admin
  SECURITY_ENABLED: false
  KC_IMPORT_ENABLED: true
  KC_INTEGRATION_ENABLED: true
  KC_LOGIN_CLIENT_SUFFIX: login-app
  KC_SERVICE_CLIENT_ID: m2m-client
  KONG_INTEGRATION_ENABLED: true
  OKAPI_INTEGRATION_ENABLED: false
# Files
files: 
  module-env: .module.env
  module-descriptors: .module-descriptors.json
# Resources
resources: 
  vault: http://vault.eureka:8200
  keycloak: http://keycloak.eureka:8080
  mgr-tenants: http://mgr-tenants.eureka:8081
  mgr-applications: http://mgr-applications.eureka:8081
  mgr-tenant-entitlements: http://mgr-tenant-entitlements.eureka:8081
# Tenants
tenants:
  - diku 
# Backend modules
backend-modules:
  # Management modules
  mgr-applications:
    port: 9901
    environment:
      # DB
      DB_DATABASE: app_manager
      DB_USERNAME: app_manager_rw
      DB_PASSWORD: superAdmin
      # Management
      MODULE_URL: http://mgr-applications.eureka:8081
      TE_URL: http://mgr-tenant-entitlements.eureka:8081
      VALIDATION_MODE: basic
  mgr-tenants:
    port: 9902
    environment:
      # DB
      DB_DATABASE: tenant_manager
      DB_USERNAME: tenant_manager_rw
      DB_PASSWORD: superAdmin
      # Management
      MODULE_URL: http://mgr-tenants.eureka:8081
      CACHE_EXPIRATION_TTL: 55s
  mgr-tenant-entitlements:
    port: 9903
    environment:
      # DB
      DB_DATABASE: tenant_entitlement
      DB_USERNAME: tenant_entitlement_rw
      DB_PASSWORD: superAdmin
      # Management
      MODULE_URL: http://mgr-tenant-entitlements.eureka:8081
      TENANT_URL: http://mgr-tenants.eureka:8081
      AM_CLIENT_URL: http://mgr-applications.eureka:8081
  # Keycloak modules
  mod-users-keycloak:
    port: 9009
    sidecar: true
    environment:
      JAVA_OPTIONS: >-
        -Dhost=okapi
        -Dstorage=postgres
        -Dpostgres_host=db
        -Dpostgres_username=okapi_rw
        -Dpostgres_password=superAdmin
  mod-login-keycloak:
    port: 9010
    sidecar: true
    environment:
      X_OKAPI_TOKEN_HEADER_ENABLED: 'true'
  mod-roles-keycloak:
    port: 9011
    sidecar: true
  mod-scheduler:
    port: 9012
    sidecar: true
  # Core Modules
  mod-permissions:
  mod-configuration:
  mod-users:
  mod-users-bl:
  mod-roles:
  mod-password-validator:
  mod-settings:
  mod-notes:
  mod-tags:
frontend-modules:
  folio_developer:
  folio_tags:
  folio_stripes-core:
  folio_notes:
  folio_stripes-smart-components: