# Registries
registries: 
  folio:
    registry-hostname: folioci
    registry-url: http://folio-registry.dev.folio.org
    install-json-url: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/install.json
  eureka:
    registry-hostname: 732722833398.dkr.ecr.us-west-2.amazonaws.com
    registry-url: https://eureka-registry.ci.folio.org
    install-json-url: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/eureka-platform.json
    sidecar-image: folio-module-sidecar:latest
    
# Shared ENV
shared-env:
  # General
  ENV: folio
  # PostgeSQL DB
  DB_HOST: db.eureka
  DB_PORT: 5432
  DB_DATABASE: okapi
  DB_USERNAME: okapi_rw
  DB_PASSWORD: superAdmin
  # Kafka Brokers
  KAFKA_HOST: kafka.eureka
  KAFKA_PORT: 9092
  # Elasticsearch
  ELASTICSEARCH_URL: http://host.docker.internal:9200
  # AWS S3 (MinIO)
  AWS_URL: http://host.docker.internal:9000
  AWS_REGION: us-east-1
  AWS_BUCKET: example-bucket
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  S3_IS_AWS: false
  S3_URL: http://host.docker.internal:9000
  S3_REGION: us-east-1
  S3_ACCESS_KEY_ID: minioadmin
  S3_SECRET_ACCESS_KEY: minioadmin
  S3_BUCKET: example-bucket
  SPLIT_FILES_ENABLED: true
  # Okapi (legacy)
  OKAPI_URL: http://api-gateway.eureka:8000
  # Consortia
  SYSTEM_USER_PASSWORD: system_user_password
  # Java
  JAVA_OPTIONS: "-Dokapi.url=http://api-gateway.eureka:8000 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -XX:MaxRAMPercentage=85.0 -Xms128m -Xmx240m"

# Cache files
cache-files: 
  module-env: .module.env
  module-descriptors: .module-descriptors.json

# Resource URLs
resource-urls: 
  vault: http://vault.eureka:8200
  keycloak: http://keycloak.eureka:8080
  mgr-tenants: http://mgr-tenants.eureka:8081
  mgr-applications: http://mgr-applications.eureka:8081
  mgr-tenant-entitlements: http://mgr-tenant-entitlements.eureka:8081

# Tenant configuration
tenant-config:
  - diku 
  - diku2 

# Backend modules
backend-modules:
  # Keycloak
  mod-users-keycloak:
    port: 9009
    deploy-module: true
    deploy-sidecar: true
    module-env:
      KC_URL: http://keycloak.eureka:8080
      KC_ADMIN_CLIENT_ID: superAdmin
      KC_LOGIN_CLIENT_SUFFIX: login-app
      JAVA_OPTIONS: >-
        -Dhost=okapi
        -Dstorage=postgres
        -Dpostgres_host=db
        -Dpostgres_username=okapi_rw
        -Dpostgres_password=superAdmin
        -Dokapi.url=http://api-gateway.eureka:8000
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  mod-login-keycloak:
    port: 9010
    deploy-module: true
    deploy-sidecar: true
    module-env:
      KC_URL: http://keycloak.eureka:8080
      KC_ADMIN_CLIENT_ID: superAdmin
      KC_LOGIN_CLIENT_SUFFIX: login-app
      KC_ADMIN_PASSWORD: admin
      X_OKAPI_TOKEN_HEADER_ENABLED: 'true'
  mod-roles-keycloak:
    port: 9011
    deploy-module: true
    deploy-sidecar: true
    module-env:
      KC_URL: http://keycloak.eureka:8080
      KC_ADMIN_CLIENT_ID: superAdmin
      KC_LOGIN_CLIENT_SUFFIX: login-app
  mod-scheduler:
    port: 9012
    deploy-module: true
    deploy-sidecar: true
    module-env:
      KC_URL: http://keycloak.eureka:8080
      KC_ADMIN_CLIENT_ID: superAdmin
      KC_LOGIN_CLIENT_SUFFIX: login-app
      JAVA_OPTIONS: >-
        -Dokapi.url=http://api-gateway.eureka:8000
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -XX:MaxRAMPercentage=85.0
        -Xms128m -Xmx240m
  mod-consortia-keycloak:
    port: 9013
    deploy-module: true
    deploy-sidecar: true
  # Core Modules
  mod-users:
    port: 30001
    deploy-module: true
    deploy-sidecar: true
  mod-users-bl:
    port: 30002
    deploy-module: true
    deploy-sidecar: true
  mod-roles:
    port: 30003
    deploy-module: true
    deploy-sidecar: true
  mod-authtoken:
    port: 30004
    deploy-module: true
    deploy-sidecar: true
  mod-permissions:
    port: 30005
    deploy-module: true
    deploy-sidecar: true
  mod-configuration:
    port: 30006
    deploy-module: true
    deploy-sidecar: true

# UI modules
ui-modules: []