name: Release CLI

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.2.3

jobs:
  test:
    name: Test CLI Help Command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          cache-dependency-path: ./eureka-cli/go.sum

      - name: Build CLI
        working-directory: ./eureka-cli
        run: go build -o eureka-cli

      - name: Run Help Command Test
        working-directory: ./eureka-cli
        run: |
          ./eureka-cli --help
          echo "Help command ran successfully"

  release:
    name: Build and Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          cache-dependency-path: ./eureka-cli/go.sum

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ./eureka-cli
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
